name = "SimpleRegressionGP"
uuid = "bc18901c-f663-4665-a286-cf64e7af24b0"
authors = ["ngiann <ngiann@gmail.com> and contributors"]
version = "0.1.0"

[deps]
MiscUtil = "e472fcb8-ab9f-4ff8-82d2-c5cadce53af3"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
